name: weighted_pcrps
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - git
  - setuptools=80.10.2
  - absl-py=2.1.0
  - apache-beam=2.64.0
  - cartopy=0.23.0
  - dask=2024.8.0
  - fsspec=2024.3.1
  - gcsfs=2024.3.1
  - matplotlib=3.8.4
  - numcodecs=0.13.1
  - numpy=2.2.6
  - pandas=2.2.3
  - scores=2.3.0
  - scipy=1.13.0
  - xarray=2025.4.0
  - zarr=2.18.3
  - pip:
      - isodisreg @ git+https://github.com/evwalz/isodisreg.git@c293eb3a126f200bf4894ecbab6157596c2a395e
      - weatherbench2 @ git+https://github.com/google-research/weatherbench2.git@d29e2692ecce309b52407d7914af3baa62bbe2b9
      - xarray-beam==0.8.0